### ISSUE TITLE
Using PΨFinder on non-human samples

### ISSUE THREAD

**Issue by tbenavi1** [SannaAb/Pseudogenes#2]
Hello,

I was wondering if it is possible to use PΨFinder on non-human samples. I see that it automatically downloads several HG19 bed files. When I run on my non-human samples, I do get plenty of alignments in the *.extractedN.bam files which seem to support the presence of processed pseudogenes, but there are no pseudogene candidates detected. I am wondering if there is some post-processing step that filters against the known human database. I do get several warnings such as "File *.extractedN.bed has inconsistent naming convention for record", which makes sense because the chromosomes for my organism are not human chromosomes. I even lowered the depth thresholds with --pseudoCandidateDepth 3 --ChimericPairDepthTreshold 5 --ChimericReadDepthTreshold 5 but still get no results. The other possibility is that the sequencing coverage for my samples is too low to be detected by PΨFinder. Thank you for any insights.

**Comment by SannaAb** [comment]
Hi, I am so sorry for the late reply. 

As it is now it only works for human samples (hg19). It extracts the cigar Ns from the bamfile to look for spliced reads. These splices are then intersected with the human annotation. Using it for other species you would need to create a gene coord and an exoncoord database file in the same format as those you find in the database folder for the tool. Then you could change the path for these files under the database function in the ppsy.py python script. If the species of interest have known pseudogenes you could generate a database file for this was well. 

I hope it works out for you, 
All the best, 

Sanna
